/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthViewRouteImport } from './routes/auth/$view'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminRolesRouteImport } from './routes/dashboard/admin/roles'
import { Route as DashboardAdminPermissionsRouteImport } from './routes/dashboard/admin/permissions'
import { Route as DashboardAdminAuditRouteImport } from './routes/dashboard/admin/audit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthViewRoute = AuthViewRouteImport.update({
  id: '/auth/$view',
  path: '/auth/$view',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminRolesRoute = DashboardAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminPermissionsRoute =
  DashboardAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminAuditRoute = DashboardAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/auth/$view': typeof AuthViewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/audit': typeof DashboardAdminAuditRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/auth/$view': typeof AuthViewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/audit': typeof DashboardAdminAuditRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/auth/$view': typeof AuthViewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/admin/audit': typeof DashboardAdminAuditRoute
  '/dashboard/admin/permissions': typeof DashboardAdminPermissionsRoute
  '/dashboard/admin/roles': typeof DashboardAdminRolesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/auth/$view'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/audit'
    | '/dashboard/admin/permissions'
    | '/dashboard/admin/roles'
    | '/dashboard/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/admin'
    | '/auth/$view'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/admin/audit'
    | '/dashboard/admin/permissions'
    | '/dashboard/admin/roles'
    | '/dashboard/admin/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/admin'
    | '/auth/$view'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/admin/audit'
    | '/dashboard/admin/permissions'
    | '/dashboard/admin/roles'
    | '/dashboard/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthViewRoute: typeof AuthViewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/$view': {
      id: '/auth/$view'
      path: '/auth/$view'
      fullPath: '/auth/$view'
      preLoaderRoute: typeof AuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/roles': {
      id: '/dashboard/admin/roles'
      path: '/roles'
      fullPath: '/dashboard/admin/roles'
      preLoaderRoute: typeof DashboardAdminRolesRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/permissions': {
      id: '/dashboard/admin/permissions'
      path: '/permissions'
      fullPath: '/dashboard/admin/permissions'
      preLoaderRoute: typeof DashboardAdminPermissionsRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/audit': {
      id: '/dashboard/admin/audit'
      path: '/audit'
      fullPath: '/dashboard/admin/audit'
      preLoaderRoute: typeof DashboardAdminAuditRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteRouteChildren {
  DashboardAdminAuditRoute: typeof DashboardAdminAuditRoute
  DashboardAdminPermissionsRoute: typeof DashboardAdminPermissionsRoute
  DashboardAdminRolesRoute: typeof DashboardAdminRolesRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminAuditRoute: DashboardAdminAuditRoute,
  DashboardAdminPermissionsRoute: DashboardAdminPermissionsRoute,
  DashboardAdminRolesRoute: DashboardAdminRolesRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthViewRoute: AuthViewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
